[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
